version: '3.5'

services:
  mariadb:
    image: "mariadb"
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: elasticdb
    volumes:
      - ./mariadb:/docker-entrypoint-initdb.d
    container_name: mariadb_scala
  elasticsearch:
    image: elasticsearch:7.1.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    container_name: elasticsearch_scala
  logstash:
    image: logstash:7.1.1
    links:
      - elasticsearch
    volumes:
      - ./logstash/input.conf:/usr/share/logstash/pipeline/input.conf
      - ./logstash/output.conf:/usr/share/logstash/pipeline/output.conf
      - ./logstash/mysql-connector-java-8.0.16.jar:/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java-8.0.16.jar
    depends_on:
      - elasticsearch
    container_name: logstash_scala